import { EMoneyBrand, NominalItem, DigitalProduct, BlogPost } from "@/types";

export const STORE_INFO = {
  name: "Arifin Store",
  domain: "arifinstore.id",
  owner: "Mokhammad Arifin Ilham",
  whatsapp: "083183787697",
  whatsappUrl: "https://wa.me/6283183787697",
  email: "admin@arifinstore.id",
  instagram: "@arifinstoredigital",
  instagramUrl: "https://instagram.com/arifinstoredigital",
  tiktok: "@arifinstoredigitall",
  tiktokUrl: "https://tiktok.com/@arifinstoredigitall",
  youtube: "@arifinstoredigital",
  youtubeUrl: "https://youtube.com/@arifinstoredigital",
  slogan: "Pusat Top-Up E-Money & Akun Digital Premium Termurah 24 Jam Nonstop",
};

// 7 E-Money Providers dengan Kode Bebas Nominal Sekalipay
export const EMONEY_BRANDS: EMoneyBrand[] = [
  {
    id: "dana",
    name: "DANA",
    code: "BBSD",
    icon: "/assets/dana-product.png",
    placeholder: "Contoh: 081234567890",
    badge: "Paling Populer",
    popular: true,
  },
  {
    id: "shopeepay",
    name: "ShopeePay",
    code: "BBSSH002",
    icon: "/assets/shopeepay-product.png",
    placeholder: "Contoh: 081234567890",
    badge: "Promo Spesial",
    popular: true,
  },
  {
    id: "gopay",
    name: "GoPay",
    code: "BBSGP",
    icon: "/assets/gopay-product.png",
    placeholder: "Contoh: 081234567890",
    badge: "Instan",
    popular: true,
  },
  {
    id: "ovo",
    name: "OVO",
    code: "BBSOVON",
    icon: "/assets/ovo-product.png",
    placeholder: "Contoh: 081234567890",
    popular: true,
  },
  {
    id: "linkaja",
    name: "LinkAja",
    code: "BBSTC",
    icon: "/assets/linkaja-product.png",
    placeholder: "Contoh: 081234567890",
  },
  {
    id: "isaku",
    name: "i.saku",
    code: "BBSAKU",
    icon: "/assets/isaku-product.png",
    placeholder: "Nomor HP Akun i.saku",
  },
  {
    id: "doku",
    name: "DOKU",
    code: "BBSDOKU",
    icon: "/assets/doku-product.png",
    placeholder: "DOKU ID / Nomor HP",
  },
  {
    id: "astrapay",
    name: "AstraPay",
    code: "BBSASTR",
    icon: "/assets/astrapay-product.png",
    placeholder: "Nomor HP AstraPay",
  },
];

// 19 Pilihan Nominal Tetap (dari backend Sekalipay Open Denom)
export const FIXED_NOMINALS: NominalItem[] = [
  { amount: 10000, label: "10.000", price: 10450, originalPrice: 11000 },
  { amount: 15000, label: "15.000", price: 15500, originalPrice: 16500 },
  { amount: 20000, label: "20.000", price: 20450, originalPrice: 21500, popular: true },
  { amount: 25000, label: "25.000", price: 25500, originalPrice: 26500 },
  { amount: 30000, label: "30.000", price: 30500, originalPrice: 32000 },
  { amount: 35000, label: "35.000", price: 35550, originalPrice: 37000 },
  { amount: 40000, label: "40.000", price: 40550, originalPrice: 42000 },
  { amount: 45000, label: "45.000", price: 45600, originalPrice: 47500 },
  { amount: 50000, label: "50.000", price: 50500, originalPrice: 52500, popular: true },
  { amount: 55000, label: "55.000", price: 55650, originalPrice: 58000 },
  { amount: 60000, label: "60.000", price: 60650, originalPrice: 63000 },
  { amount: 65000, label: "65.000", price: 65700, originalPrice: 68500 },
  { amount: 70000, label: "70.000", price: 70700, originalPrice: 73500 },
  { amount: 75000, label: "75.000", price: 75750, originalPrice: 79000 },
  { amount: 80000, label: "80.000", price: 80750, originalPrice: 84000 },
  { amount: 85000, label: "85.000", price: 85800, originalPrice: 89500 },
  { amount: 90000, label: "90.000", price: 90800, originalPrice: 94500 },
  { amount: 95000, label: "95.000", price: 95850, originalPrice: 99500 },
  { amount: 100000, label: "100.000", price: 100500, originalPrice: 104000, popular: true },
];

// 7 Produk Digital Pilihan ProdSeller
export const DIGITAL_PRODUCTS: DigitalProduct[] = [
  {
    id: "gemini-pro-18m",
    name: "Gemini Pro 18Months (link)",
    category: "Artificial Intelligence",
    duration: "18 Bulan (Full Garansi)",
    price: 185000,
    originalPrice: 450000,
    rating: 4.9,
    soldCount: 842,
    requiresEmail: false,
    badge: "BEST SELLER ⭐",
    description: "Aktivasi Google Gemini Pro 18 Bulan resmi via direct redemption link. Akses fitur AI tercanggih, 1M+ token context window, dan kecepatan tinggi.",
    features: [
      "Aktivasi Instan via Link Resmi",
      "Durasi 18 Bulan Penuh",
      "Garansi Replacement Aktif",
      "Bisa Akun Pribadi",
    ],
    slug: "gemini-pro-18months",
  },
  {
    id: "duolingo-super-12m",
    name: "Duolingo Super 12M",
    category: "Edukasi & Bahasa",
    duration: "12 Bulan (1 Tahun)",
    price: 49000,
    originalPrice: 129000,
    rating: 5.0,
    soldCount: 1250,
    requiresEmail: true,
    badge: "POPULER 🔥",
    description: "Belajar bahasa asing tanpa batasan nyawa (Unlimited Hearts), bebas iklan, dan review kesalahan otomatis selama 1 tahun penuh.",
    features: [
      "Unlimited Hearts (Nyawa Tanpa Batas)",
      "Bebas Iklan Selamanya",
      "Practice Hub & Mistake Review",
      "Garansi 365 Hari",
    ],
    slug: "duolingo-super-12m",
  },
  {
    id: "notion-plus",
    name: "Notion Plus",
    category: "Produktivitas",
    duration: "12 Bulan (1 Tahun)",
    price: 85000,
    originalPrice: 240000,
    rating: 4.9,
    soldCount: 460,
    requiresEmail: true,
    badge: "REKOMENDASI 💼",
    description: "Workspace kolaborasi lengkap untuk individu dan tim profesional. Unlimited file uploads, 30 days page history, dan akses workspace canggih.",
    features: [
      "Unlimited File Uploads",
      "30-day Page History",
      "Invite Hingga 100 Guest",
      "Full Fitur Notion AI Ready",
    ],
    slug: "notion-plus",
  },
  {
    id: "adobe-express-12m",
    name: "Adobe Express 12M",
    category: "Desain Grafis",
    duration: "12 Bulan (1 Tahun)",
    price: 95000,
    originalPrice: 320000,
    rating: 4.8,
    soldCount: 310,
    requiresEmail: true,
    description: "Platform desain konten visual all-in-one dari Adobe dengan ribuan template premium, font Adobe, dan fitur AI generative removal.",
    features: [
      "Ribuan Template Adobe Premium",
      "Akses Adobe Stock Photos",
      "Fitur AI Text-to-Image",
      "Garansi 1 Tahun Penuh",
    ],
    slug: "adobe-express-12m",
  },
  {
    id: "office-365-plus",
    name: "Microsoft Office 365 Plus 1 year",
    category: "Software & Cloud",
    duration: "12 Bulan (1 Tahun)",
    price: 99000,
    originalPrice: 280000,
    rating: 4.9,
    soldCount: 680,
    requiresEmail: false,
    description: "Paket lengkap Word, Excel, PowerPoint, Outlook untuk 5 perangkat (PC/Mac/HP) plus penyimpanan cloud OneDrive 1TB.",
    features: [
      "Aplikasi Office Lengkap Original",
      "Support 5 Device Sekaligus",
      "Cloud Storage OneDrive 1TB",
      "Update Resmi Microsoft",
    ],
    slug: "microsoft-office-365",
  },
  {
    id: "jetbrains-edu-12m",
    name: "JetBrains Edu Pack 12m",
    category: "Developer Tools",
    duration: "12 Bulan (1 Tahun)",
    price: 79000,
    originalPrice: 250000,
    rating: 4.8,
    soldCount: 220,
    requiresEmail: true,
    description: "All Products Pack dari JetBrains untuk programmer: IntelliJ IDEA Ultimate, PyCharm, WebStorm, PhpStorm, CLion, GoLand, dll.",
    features: [
      "Akses Semua IDE JetBrains",
      "Lisensi 12 Bulan Aktif",
      "Bisa Update ke Versi Terbaru",
      "Garansi Support 1 Tahun",
    ],
    slug: "jetbrains-edu-pack",
  },
  {
    id: "duolingo-12m-new",
    name: "Duolingo 12M new method",
    category: "Edukasi & Bahasa",
    duration: "12 Bulan (Metode Baru)",
    price: 45000,
    originalPrice: 110000,
    rating: 4.7,
    soldCount: 540,
    requiresEmail: true,
    description: "Aktivasi Duolingo 12 Bulan metode tautan invite keluarga instan tanpa kendala region.",
    features: [
      "Metode Aktivasi Baru Anti Rollback",
      "Fitur Super Aktif Penuh",
      "Proses Cepat 5 Menit",
      "Garansi Penggantian",
    ],
    slug: "duolingo-12m-new-method",
  },
];

// Blog Posts untuk SEO
export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "Panduan Lengkap Cara Top Up E-Wallet Bebas Biaya Admin di Arifin Store",
    slug: "panduan-lengkap-topup-e-wallet",
    category: "E-Wallet",
    summary: "Simak tutorial mudah isi saldo DANA, GoPay, ShopeePay, OVO, dan LinkAja dengan proses instan 5 detik melalui pembayaran QRIS otomatis.",
    content: "Di era serba digital saat ini, kebutuhan isi ulang saldo e-wallet seperti DANA, ShopeePay, OVO, dan GoPay sudah menjadi kebutuhan sehari-hari...",
    author: "Mokhammad Arifin Ilham",
    readTime: "3 Menit",
    publishedAt: "29 September 2026",
    tags: ["Topup E-Wallet", "DANA", "ShopeePay", "QRIS"],
  },
  {
    id: "2",
    title: "Mengapa Google Gemini Pro 18 Months Jadi Pilihan Terbaik untuk Pekerja Kreatif?",
    slug: "keunggulan-gemini-pro-18-months",
    category: "AI Tools",
    summary: "Eksplorasi context window 1 juta token, integrasi data real-time, dan hemat biaya langganan hingga 70% melalui Arifin Store.",
    content: "Google Gemini Pro membawa revolusi dalam produktivitas kerja berkat kapasitas pemrosesan konteks hingga jutaan token...",
    author: "Mokhammad Arifin Ilham",
    readTime: "4 Menit",
    publishedAt: "28 September 2026",
    tags: ["Gemini Pro", "Google AI", "Produk Digital"],
  },
  {
    id: "3",
    title: "Tips Maksimalkan Belajar Bahasa Asing dengan Duolingo Super 12M",
    slug: "tips-belajar-bahasa-duolingo-super",
    category: "Edukasi",
    summary: "Belajar kosakata tanpa batasan nyawa dan bebas iklan. Dapatkan trik konsisten mempertahankan streak harian dengan mudah.",
    content: "Konsistensi adalah kunci utama dalam menguasai bahasa baru. Dengan fitur Duolingo Super, Anda tidak perlu lagi menunggu nyawa terisi ulang...",
    author: "Mokhammad Arifin Ilham",
    readTime: "3 Menit",
    publishedAt: "26 September 2026",
    tags: ["Duolingo Super", "Belajar Bahasa", "Edukasi"],
  },
  {
    id: "4",
    title: "Cara Mengatur Manajemen Proyek Profesional Menggunakan Notion Plus",
    slug: "manajemen-proyek-dengan-notion-plus",
    category: "Produktivitas",
    summary: "Optimalkan workspace Notion Plus Anda untuk mengelola sprint, dokumentasi tim, dan database otomatis tanpa batas ukuran upload.",
    content: "Notion Plus memberikan kebebasan bagi para kreator dan tim untuk membangun sistem operasi digital sendiri...",
    author: "Mokhammad Arifin Ilham",
    readTime: "5 Menit",
    publishedAt: "24 September 2026",
    tags: ["Notion Plus", "Produktivitas", "Workspace"],
  },
];
